language: python
python:
  - "3.7"
env:
  - COVERALLS_SERVICE_NAME=grassroot-assistance
  - COVERALLS_REPO_TOKEN=abc12345
install:
  - pip install -r requirements.txt
script:
  - pytest test.py -v --cov=.
after_success:
  - coveralls --service=github
