language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
env:
  - COVERALLS_REPO_TOKEN=VgsayYJNvIxQLAi23mC4nJstHkj2fAvzs
script:
  - pytest test.py --doctest-modules -v --cov=.
after_success:
  - coveralls
