language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
script:
  - pytest test.py --doctest-modules -v --cov=.
  - coverage run --source=. test.py test
after_success:
  - coveralls --service=github
